name: Kabads' blog
description: Musing, mutterings and murmurings.
url: http://kabads.monkeez.org
site-url: kabads.monkeez.org
paginate: 10
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: redcarpet
gems:
 - jekyll-sitemap
 - jekyll-paginate