baseURL = "https://kabads.monkeez.org/"
languageCode = "en-us"
title = "Kabads - musings, mutterings and murmerings"
theme = "whiteplain"
[[menu.main]]
name = "Categories"
identifier = "categories"
url = "/categories/"
weight = 1
[[menu.main]]
name="About"
identifier = "about"
url = "/about/"
weight = 4
twitter = "kabads"
copyright = "&copy; Copyright 2018 A Cripps."
[taxonomies]
category = "categories"
tag = "tags"
