baseURL = "https://kabads.monkeez.org/"
languageCode = "en-us"
title = "Kabads - musings, mutterings and murmerings"
<<<<<<< HEAD
theme = "hugo_theme_beg"
=======
theme = "whiteplain"
[[menu.main]]
name = "Categories"
identifier = "categories"
url = "/categories/"
weight = 1
[[menu.main]]
name="About"
identifier = "about"
url = "/about/"
weight = 4
twitter = "kabads"
copyright = "&copy; Copyright 2018 A Cripps."
[taxonomies]
category = "categories"
tag = "tags"

>>>>>>> b16940f998a8a6ccef3e3c31b8d5ce8b6bc92f8f
